# Just configuration file for running commands.
#
# For more information, visit https://just.systems.

set script-interpreter := ["nu"]
set shell := ["nu", "--commands"]
export DENO_INSTALL_ROOT := justfile_directory() / ".vendor/lib/deno"
export NO_MKDOCS_2_WARNING := "1"
export PATH := if os() == "windows" {
  justfile_directory() / ".vendor/bin;" + justfile_directory() /
  ".vendor/lib/deno/bin;" + env("PATH")
} else {
  justfile_directory() / ".vendor/bin:" + justfile_directory() /
  ".vendor/lib/deno/bin:" + env("PATH")
}

# Build project for release.
build:
  uv build --out-dir build/dist

# Run continuous integration pipeline.
ci: setup lint test doc build

# Build documentation.
[script]
doc:
  mkdir build/site
  cp README.md doc/index.md
  cp CONTRIBUTING.md doc/
  uv run mkdocs build --strict

# Format project files.
format +paths=".":
  prettier --write {{ "{{" }}paths{{ "}}" }}
  uv run ruff format {{ "{{" }}paths{{ "}}" }}

{% if cookiecutter.project_cli -%}
# Install project program.
[script]
install: setup build
  let name = "{{ cookiecutter.project_name }}"
  let repo = "{{ "{{" }}justfile_directory(){{ "}}" }}" | path expand
  let package = glob build/dist/*.whl | first
  let installer = ["uv" "pipx" "python3"]
  | each { which --all $in | get path }
  | flatten
  | where { not ($in | path expand | str starts-with $repo) }
  | first
  if ($installer | is-empty) {
    error make "Unable to find an external Python package installer."
  }
  match ($installer | path basename) {
    uv => { ^$installer tool install $package }
    pipx => { ^$installer install $package }
    python3 => { ^$installer -m pip install $package }
  }
  print $"Installed ($name) to (which $name | get 0.path)"

{% endif -%}
# Analyze files for issues.
lint +paths=".":
  prettier --check {{ "{{" }}paths{{ "}}" }}
  uv run ruff format --check {{ "{{" }}paths{{ "}}" }}
  uv run ruff check {{ "{{" }}paths{{ "}}" }}
  uv run ty check {{ "{{" }}paths{{ "}}" }}

# List available commands.
[default]
@list:
  just --list

# Run Nushell in project environment.
[no-exit-message]
@nu *args="nu --login":
  nu --commands "{{ "{{" }}args{{ "}}" }}"

{% if cookiecutter.project_cli -%}
# Run project (use DEBUG=1 for debugger).
[no-exit-message, script]
run *args:
  if ($env.DEBUG? | into bool --relaxed) {
    uv run python -m pdb -m {{ cookiecutter.__project_package }} {{ "{{" }}args{{ "}}" }}
  } else {
    uv run {{ cookiecutter.__project_package }} {{ "{{" }}args{{ "}}" }}
  }

{% endif -%}
# Install development tools and dependencies.
[script]
setup: _setup
  if (which deno | is-empty) {
    print "Installing Deno."
    http get https://scruffaluff.github.io/picoware/install/deno.nu
    | nu -c $"($in | decode); main --preserve-env --dest .vendor/bin"
  }
  print $"Using (deno -V)."
  if (which prettier | is-empty) {
    print "Installing Prettier."
    deno install --allow-all --global npm:prettier
  }
  print $"Using Prettier (prettier --version)."
  if (which uv | is-empty) {
    print "Installing Uv."
    http get https://scruffaluff.github.io/picoware/install/uv.nu
    | nu -c $"($in | decode); main --preserve-env --dest .vendor/bin"
  }
  print $"Using (uv --version)."
  print "Installing Python packages with Uv."
  if ($env.INIT? | into bool --relaxed) {
    uv sync
    just format
  } else {
    uv sync --locked
  }

[unix]
_setup:
  #!/usr/bin/env sh
  set -eu
  if [ ! -x "$(command -v nu)" ]; then
    echo 'Installing Nushell.'
    curl --fail --location --show-error \
      https://scruffaluff.github.io/picoware/install/nushell.sh | sh -s -- \
      --preserve-env --dest .vendor/bin
  fi
  echo "Using Nushell $(nu --version)."

[windows]
_setup:
  #!powershell.exe
  $ErrorActionPreference = 'Stop'
  $ProgressPreference = 'SilentlyContinue'
  $PSNativeCommandUseErrorActionPreference = $True
  if (-not (Get-Command -ErrorAction SilentlyContinue nu)) {
    Write-Output 'Installing Nushell.'
    $NushellScript = Invoke-WebRequest -UseBasicParsing -Uri `
      https://scruffaluff.github.io/picoware/install/nushell.ps1
    Invoke-Expression "& { $NushellScript } --preserve-env --dest .vendor/bin"
  }
  Write-Output "Using Nushell $(nu --version)."

# Run tests (use DEBUG=1 for debugger).
[script]
test *args:
  if ($env.DEBUG? | into bool --relaxed) {
    uv run pytest --cov --pdb {{ "{{" }}args{{ "}}" }}
  } else {
    uv run pytest --cov {{ "{{" }}args{{ "}}" }}
  }

# Run Uv in project environment.
[no-exit-message]
@uv *args:
  uv {{ "{{" }}args{{ "}}" }}
