# MkDocs static site generator configuration file.
#
# For more information, visit https://mkdocs.org/user-guide/configuration.

---
docs_dir: doc
extra_javascript:
  - https://unpkg.com/mermaid@11.12.2/dist/mermaid.min.js
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
plugins:
  - mkdocstrings
  - search
repo_name: {{ cookiecutter.project_name }}
repo_url: {{ cookiecutter.project_repository }}
site_description: |
  {{ cookiecutter.project_description }}
site_dir: build/site
site_name: {{ cookiecutter.project_name }}
site_url: {{ cookiecutter.project_repository }}
theme:
  features:
    - content.code.copy
    - navigation.tabs
  name: material
  palette:
    accent: cyan
    primary: teal
