# MkDocs static site generator configuration file.
#
# For more information, visit https://www.mkdocs.org/user-guide/configuration/.

---
docs_dir: doc
extra_javascript:
  - https://unpkg.com/mermaid@11.10.1/dist/mermaid.min.js
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
nav:
  - Home:
      - README: index.md
      - Contributing: CONTRIBUTING.md
  - Usage: usage/index.md
  - API Reference: api/index.md
plugins:
  - mkdocstrings
  - search
repo_name: {{ cookiecutter.project_name }}
repo_url: {{ cookiecutter._project_repository }}
site_description: |
  {{ cookiecutter.project_description }}
site_dir: build/site
site_name: {{ cookiecutter.project_name }}
site_url: {{ cookiecutter._project_homepage }}
theme:
  featues:
    - navigation.tabs
  name: material
  palette:
    accent: cyan
    primary: teal
