# Just configuration file for running commands.
#
# For more information, visit https://just.systems.

set script-interpreter := ["nu"]
set shell := ["nu", "--commands"]
export PATH := if os() == "windows" {
  justfile_directory() / ".vendor/bin;" + justfile_directory() /
  ".vendor/cargo/bin;" + env("PATH")
} else {
  justfile_directory() / ".vendor/bin:" + justfile_directory() /
  ".vendor/cargo/bin:" + env("PATH")
}

# Execute CI workflow commands.
ci: setup lint doc build test

# Build distribution package.
build:
  cargo build --release

# Wrapper to Cargo.
[no-exit-message]
@cargo *args:
  cargo {{ "{{" }}args{{ "}}" }}

# Build documentation.
[script]
doc:
  cargo doc --no-deps
  '<meta content="0; url={{ cookiecutter.__project_package }}/index.html" http-equiv="refresh" />'
  | save --force target/doc/index.html

# Fix code formatting.
format:
  {% if cookiecutter.project_prettier -%}
  deno run --allow-all npm:prettier --write .
  {% endif -%}
  cargo fmt --

# Run code analyses.
lint:
  {% if cookiecutter.project_prettier -%}
  deno run --allow-all npm:prettier --check .
  {% endif -%}
  cargo fmt -- --check
  cargo clippy --all -- -D clippy::all -D clippy::cargo -D clippy::nursery -D \
    clippy::pedantic -D warnings

# List all commands available in justfile.
[default]
@list:
  just --list

# Wrapper to Nushell.
[no-exit-message]
@nu *args:
  nu --commands "{{ "{{" }}args{{ "}}" }}"

{% if cookiecutter.project_cli -%}
# Run project command line interface.
[no-exit-message]
@run *args:
  cargo run -- {{ "{{" }}args{{ "}}" }}

{% endif -%}
# Install development dependencies.
[script]
setup: _setup
  if (which cargo | is-empty) {
    print "Installing Cargo."
    http get https://scruffaluff.github.io/picoware/install/cargo.nu
    | nu -c $"($in | decode); main --preserve-env --dest .vendor/cargo"
  }
  print $"Using (cargo --version)."
  {% if cookiecutter.project_prettier -%}
  if (which deno | is-empty) {
    print "Installing Deno."
    http get https://scruffaluff.github.io/picoware/install/deno.nu
    | nu -c $"($in | decode); main --preserve-env --dest .vendor/bin"
  }
  print $"Using (deno -V)."
  {% endif -%}
  if (which rust-script | is-empty) {
    print "Installing Rust Script."
    http get https://scruffaluff.github.io/picoware/install/rust-script.nu
    | nu -c $"($in | decode); main --preserve-env --dest .vendor/bin"
  }
  print $"Using (rust-script --version)."
  print "Installing Rust packages with Cargo."
  if ($env.JUST_INIT? | is-empty) {
    cargo fetch --locked
  } else {
    cargo fetch
  }

[unix]
_setup:
  #!/usr/bin/env sh
  set -eu
  if [ ! -x "$(command -v nu)" ]; then
    echo 'Installing Nushell.'
    curl --fail --location --show-error \
      https://scruffaluff.github.io/picoware/install/nushell.sh | sh -s -- \
      --preserve-env --dest .vendor/bin
  fi
  echo "Using Nushell $(nu --version)."

[windows]
_setup:
  #!powershell.exe
  $ErrorActionPreference = 'Stop'
  $ProgressPreference = 'SilentlyContinue'
  $PSNativeCommandUseErrorActionPreference = $True
  if (-not (Get-Command -ErrorAction SilentlyContinue nu)) {
    Write-Output 'Installing Nushell.'
    $NushellScript = Invoke-WebRequest -UseBasicParsing -Uri `
      https://scruffaluff.github.io/picoware/install/nushell.ps1
    Invoke-Expression "& { $NushellScript } --preserve-env --dest .vendor/bin"
  }
  Write-Output "Using Nushell $(nu --version)."

# Run test suites.
test *args:
  cargo test {{ "{{" }}args{{ "}}" }}
