# Just configuration file for running commands.
#
# For more information, visit https://just.systems.

set script-interpreter := ["nu"]
set shell := ["nu", "--commands"]
export DENO_INSTALL_ROOT := justfile_directory() / ".vendor/lib/deno"
export PATH := if os() == "windows" {
  justfile_directory() / ".vendor/bin;" + justfile_directory() /
  ".vendor/lib/cargo/bin;" + justfile_directory() / ".vendor/lib/deno/bin;"
  + env("PATH")
} else {
  justfile_directory() / ".vendor/bin:" + justfile_directory() /
  ".vendor/lib/cargo/bin:" + justfile_directory() / ".vendor/lib/deno/bin:"
  + env("PATH")
}

# Run continuous integration pipeline.
ci: setup lint test doc build

# Build project for release.
build:
  cargo build --release

# Run Cargo in project environment.
[no-exit-message]
@cargo *args:
  cargo {{ "{{" }}args{{ "}}" }}

# Build documentation.
[script]
doc:
  cargo doc --no-deps
  '<meta content="0; url={{ cookiecutter.__project_package }}/index.html" http-equiv="refresh" />'
  | save --force target/doc/index.html

# Format project files.
format:
  prettier --write .
  cargo fmt --

# Install project program.
[script]
install: setup build
  let dest = "{{ "{{" }}home_directory(){{ "}}" }}/.local/bin"
  let ext = if $nu.os-info.name == "windows" { ".exe" } else { "" }
  mkdir $dest
  cp $"target/release/{{ cookiecutter.__project_package }}($ext)" $"($dest)/"
  if not ($dest in $env.PATH) {
    print --stderr $"Installation folder '$(dest)' is not in the system path."
    print --stderr "Update system path manually to complete installation."
  }

# Analyze files for issues.
lint:
  prettier --check .
  cargo fmt -- --check
  cargo clippy --all -- -D clippy::all -D clippy::cargo -D clippy::nursery -D \
    clippy::pedantic -D warnings

# List available commands.
[default]
@list:
  just --list

# Run Nushell in project environment.
[no-exit-message]
@nu *args="nu --login":
  nu --commands "{{ "{{" }}args{{ "}}" }}"

{% if cookiecutter.project_cli -%}
# Run project (use DEBUG=1 for debugger).
[no-exit-message, script]
run *args:
  if ($env.DEBUG? | into bool --relaxed) {
    cargo build
    rust-lldb target/debug/{{ cookiecutter.__project_package }} -- {{ "{{" }}args{{ "}}" }}
  } else {
    cargo run -- {{ "{{" }}args{{ "}}" }}
  }

{% endif -%}
# Install development tools and dependencies.
[script]
setup: _setup
  if (which cargo | is-empty) {
    print "Installing Cargo."
    http get https://scruffaluff.github.io/picoware/install/cargo.nu
    | nu -c $"($in | decode); main --preserve-env --dest .vendor/lib/cargo"
  }
  print $"Using (cargo --version)."
  if (which deno | is-empty) {
    print "Installing Deno."
    http get https://scruffaluff.github.io/picoware/install/deno.nu
    | nu -c $"($in | decode); main --preserve-env --dest .vendor/bin"
  }
  print $"Using (deno -V)."
  if (which prettier | is-empty) {
    print "Installing Prettier."
    deno install --allow-all --global npm:prettier
  }
  print $"Using Prettier (prettier --version)."
  if (which rust-script | is-empty) {
    print "Installing Rust Script."
    http get https://scruffaluff.github.io/picoware/install/rust-script.nu
    | nu -c $"($in | decode); main --preserve-env --dest .vendor/bin"
  }
  print $"Using (rust-script --version)."
  print "Installing Rust packages with Cargo."
  if ($env.INIT? | into bool --relaxed) {
    cargo fetch
    just format
  } else {
    cargo fetch --locked
  }

[unix]
_setup:
  #!/usr/bin/env sh
  set -eu
  if [ ! -x "$(command -v nu)" ]; then
    echo 'Installing Nushell.'
    curl --fail --location --show-error \
      https://scruffaluff.github.io/picoware/install/nushell.sh | sh -s -- \
      --preserve-env --dest .vendor/bin
  fi
  echo "Using Nushell $(nu --version)."

[windows]
_setup:
  #!powershell.exe
  $ErrorActionPreference = 'Stop'
  $ProgressPreference = 'SilentlyContinue'
  $PSNativeCommandUseErrorActionPreference = $True
  if (-not (Get-Command -ErrorAction SilentlyContinue nu)) {
    Write-Output 'Installing Nushell.'
    $NushellScript = Invoke-WebRequest -UseBasicParsing -Uri `
      https://scruffaluff.github.io/picoware/install/nushell.ps1
    Invoke-Expression "& { $NushellScript } --preserve-env --dest .vendor/bin"
  }
  Write-Output "Using Nushell $(nu --version)."

# Run tests (use DEBUG=1 for debugger).
[script]
test *args:
  if ($env.DEBUG? | into bool --relaxed) {
    let programs = cargo test --no-run --message-format json -- {{ "{{" }}args{{ "}}" }}
    | lines | each { $in | from json | get --optional executable }
    | where ($in | path basename) != "{{ cookiecutter.__project_package }}"
    for program in $programs {
      let result = ^$program | complete
      if $result.exit_code == 0 {
        print $"($result.stdout)\n($result.stderr)"
      } else {
        rust-lldb --source data/test.lldb $program
      }
    }
  } else {
    cargo test --no-fail-fast -- {{ "{{" }}args{{ "}}" }}
  }
