# Just configuration file for running commands.
#
# For more information, visit https://just.systems.

set script-interpreter := ["nu"]
set shell := ["nu", "--commands"]
set unstable := true
set windows-shell := ["nu", "--commands"]
export PATH := if os() == "windows" {
  justfile_dir() / ".vendor/bin;" + env("PATH")
} else {
  justfile_dir() / ".vendor/bin:" + env("PATH")
}

# List all commands available in justfile.
list:
  @just --list

# Execute CI workflow commands.
ci: lint test

# Run code analyses.
lint:
  uv run ruff format --check .
  uv run ruff check .
  uv run mypy .

# Run test suites.
test *args:
  uv run pytest {{args}}

# Wrapper to Uv.
[no-exit-message]
@uv *args:
  uv {{args}}

