# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: main

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      debug:
        default: false
        description: Use Tmate session for debugging
        type: boolean
      job:
        description: CI job to run
        options:
          - build
          - pages
          - release
        required: true
        type: choice
      os:
        description: Operating system
        options:
          - macos
          - ubuntu
          - windows
        required: true
        type: choice

env:
  DENO_DIR: "${{ github.workspace }}/.vendor/deno"
  UV_CACHE_DIR: "${{ github.workspace }}/.vendor/uv"

jobs:
  build:
    if: >-
      ${{ github.ref_type == 'branch' && github.event_name !=
      'workflow_dispatch' || inputs.job == 'build' }}
    name: Run code analyses and test suites
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: >-
          ${{ inputs.os && fromJson(format('["{0}"]',inputs.os)) ||
          fromJson('["macos","ubuntu","windows"]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('uv.lock') }}
          path: |
            .vendor
            .venv
      - if: ${{ runner.os == 'Windows' }}
        name: Install Just for Windows
        run: >-
          powershell { iex "& { $(iwr -useb
          https://scruffaluff.github.io/picoware/install/just.ps1) } --dest
          C:\Windows" }
      - if: ${{ runner.os != 'Windows' }}
        name: Install Just for Unix
        run: >-
          curl -LSfs https://scruffaluff.github.io/picoware/install/just.sh | sh
          -s -- --global
      - name: Run CI workflow commands
        run: just ci
      - if: ${{ always() && inputs.debug }}
        name: Launch Tmate session if debug enabled
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3

  pages:
    environment:
      name: github-pages
    if: >-
      ${{ github.ref == 'refs/heads/main' && github.event_name !=
      'workflow_dispatch' || inputs.job == 'pages' }}
    name: Build and publish documentation
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache packages
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ hashFiles('uv.lock') }}
          path: |
            .vendor
            .venv
      - name: Install Just
        run: >-
          curl -LSfs https://scruffaluff.github.io/picoware/install/just.sh | sh
          -s -- --global
      - name: Build documentation
        run: just setup doc
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          name: pages
          path: build/site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: pages
      - if: ${{ always() && inputs.debug }}
        name: Launch Tmate session if debug enabled
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3

  release:
    if: >-
      ${{ github.ref_type == 'tag' && github.event_name != 'workflow_dispatch'
      || inputs.job == 'release' }}
    name: Make GitHub release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body: >-
            See the
            [changelog](https://github.com/scruffaluff/templates/blob/${{
            github.ref_name }}/CHANGELOG.md) for more information.
          name: Templates ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
      - if: ${{ always() && inputs.debug }}
        name: Launch Tmate session if debug enabled
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
